### ISSUE TITLE
ClassCastException: newBiospheresMod.BlockDome cannot be cast to net.minecraft.block.BlockAnvil

### ISSUE THREAD

**Issue by TheLoneWolfling** [BrainSlugs83/NewBiospheresMod#15]
java.lang.ClassCastException: newBiospheresMod.BlockDome cannot be cast to net.minecraft.block.BlockAnvil
      at net.minecraft.client.renderer.RenderBlocks.func_147800_a(RenderBlocks.java:8083)
      at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:446)
      at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
      at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:271)
      at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
      at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
      at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)
      at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
      at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
      at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
      at net.minecraft.client.main.Main.main(SourceFile:148)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
      at java.lang.reflect.Method.invoke(Unknown Source)
      at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
      at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
      at java.lang.reflect.Method.invoke(Unknown Source)
      at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
      at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
      at org.multimc.EntryPoint.listen(EntryPoint.java:165)
      at org.multimc.EntryPoint.main(EntryPoint.java:54)

Happens every time I search for an anvil in the creative menu with 0.85.

**Comment by BrainSlugs83** [comment]
Ooh.  Ouch.  Will make this a high priority fix.

**Comment by BrainSlugs83** [comment]
Should be fixed in latest -- didn't remove the block dome yet -- but for now, I made it just so that anvil isn't a valid blockdome (if you try to use it, it will just use the regular anvil block instead).

**Comment by TheLoneWolfling** [comment]
If you're going to be hackish, at least be correctly hackish.

This hack does not fix the issue for any other (i.e. mod) blocks that use custom renderers and (rightfully) assume that if they're being called to render a block it's the type of block they executed to render.

This hack also doesn't fix it for fences, stairs, walls, glass panes (normal + stained), fence gates, beacons, hoppers, ...

A better version would be to stick this (static) code somewhere:

    final static BitSet b;

    b = new BitSet();
    b.set(40); // BlockDoublePlant
    b.set(11); // BlockFence
    b.set(9); // BlockRailBase
    b.set(3); // BlockFire
    b.set(10); // BlockStairs
    b.set(27); // BlockDragonEgg
    b.set(32); // BlockWall
    b.set(15); // BlockRedstoneRepeater
    b.set(36); // BlockRedstoneDiode
    b.set(37); // BlockRedstoneComparator
    b.set(18); // BlockPane
    b.set(21); // BlockFenceGate
    b.set(24); // BlockCauldron
    b.set(33); // BlockFlowerPot
    b.set(35); // BlockAnvil
    b.set(25); // BlockBrewingStand
    b.set(26); // BlockEndPortalFrame
    b.set(28); // BlockCocoa
    b.set(34); // BlockBeacon
    b.set(38); // BlockHopper

(Is it sad that I used Python to generate the above code from RenderBlock?)

And then in GetDomeBlock replace [this](https://github.com/BrainSlugs83/NewBiospheresMod/commit/f745f213003fa7dd884ff4ffea7d2fa4d3e3f74c#diff-756f84a5686d321e361597e8e27ab7e6R79) with this:

    if (b.get(baseBlock.getRenderType()))
        return baseBlock;

But again, this will break with any mod renderer that does a cast.

It also breaks with a number of renderers that check block IDs directly to determine behavior. (Minecraft: *not* the epitome of good design. To put it mildly.)

But a better method would be to have a config option to enable / disable BlockDome for a given block.

Alternatively, have an option to, for a specific block, call your own rendering handler (`ISimpleBlockRenderingHandler`), that sets the block to the mirrored block, calls the delegated handler, then sets the block back. But again, this is (even more) hacky.

**Comment by TheLoneWolfling** [comment]
This hack does not fix the issue for any other (i.e. mod) blocks that use custom renderers and (rightfully) assume that if they're being called to render a block it's the type of block they executed to render.

I'm also wondering about hoppers,

A better method would be to have a config option to enable / disable BlockDome for a given block.

Alternatively, designate your own rendering handler (an instance of `ISimpleBlockRenderingHandler`), that tries to call the delegated handler, with a fallback.

I may do up a pull request that does exactly this.

**Comment by BrainSlugs83** [comment]
Still haven't had a chance to look at that pull request (will take a look this weekend). -- Doesn't the current BlockDome class call the original class (for things like material and renderer) and return them properly?

It seems like this is a lot of extra work that we're doing manually where we should just be letting the original class handle it itself.

Also, I was thinking about the race-condition solution you mentioned before (i.e. set the block to the correct one, before calling the original method, then setting it back in a finally/etc. before returning).

What if instead, we just passed in a different IWorld object -- one that just wrapped the original object for all interface calls, except for get -- where if the object was a BlockDome -- we pass back the BlockDomes imitated object instead -- then when we call those methods, and they check the type of the current block via our IWorld object, they get back the correct information...

It still wouldn't work for server / client (since you need extra blocks), but it's a thought.

**Comment by BrainSlugs83** [comment]
(Re-opening this -- thought it was open. -- since I haven't done the pull request yet.)
